networks:
  guacnetwork_compose:
    driver: bridge
  vulnerable_network:
    driver: bridge

# services
services:

  # guacd
  guacd:
    container_name: guacd_compose
    image: guacamole/guacd
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
    ports:
      - 4822:4822/tcp
  # postgres
  postgres:
    container_name: postgres_guacamole_compose
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      - guacnetwork_compose
    restart: always
    volumes:
      - ./init:/docker-entrypoint-initdb.d:z
      - ./data:/var/lib/postgresql/data:Z
    ports:
      - 5432:5432/tcp

  # guacamole
  guacamole:
    container_name: guacamole_compose
    group_add:
      - "1000"
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
      RECORDING_SEARCH_PATH: /record
    image: guacamole/guacamole
    networks:
      - guacnetwork_compose
    volumes:
      - ./record:/record:rw
    ports:
## enable next line if not using nginx
      - 8080:8080/tcp # Guacamole is on :8080/guacamole, not /.
## enable next line when using nginx
    ##- 8080/tcp
    restart: always


  kali_red1:
      build:
        context: .
        dockerfile: Dockerfile.kali_red
      ports:
        - "3389:3389"
      privileged: true 
      networks:
        - guacnetwork_compose
        - vulnerable_network

  kali_red2:
    build:
      context: .
      dockerfile: Dockerfile.kali_red
    ports:
      - "3390:3389"
    privileged: true 
    networks:
      - guacnetwork_compose
      - vulnerable_network

  kali_red3:
    build:
      context: .
      dockerfile: Dockerfile.kali_red
    ports:
      - "3391:3389"
    privileged: true 
    networks:
      - guacnetwork_compose
      - vulnerable_network

  vuln_web:
    build:
      context: .
      dockerfile: Dockerfile.vuln_web
    ports:
      - "8081:80"     
    networks:
      - vulnerable_network
    restart: unless-stopped



