# Use the official Kali Linux base image
FROM kalilinux/kali-rolling

# Set environment variables to prevent interactive prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

LABEL maintainer="kali_red"
LABEL description="Kali Linux Red Team"



# Update and install necessary packages
RUN apt-get update && apt-get install -y \
    wget \
    bzip2 \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    nmap \
    gobuster \
    dirb \
    masscan \
    sudo \
    dnsenum \
    dnsrecon \
    whois \
    curl \
    nikto \
    metasploit-framework \
    exploitdb \
    smbclient \
    hydra \
    sqlmap \
    mimikatz \
    powershell \
    tcpdump \
    binwalk \
    wireshark \
    hashcat \
    john \
    hydra \
    aircrack-ng \
    net-tools \
    netcat-traditional \
    python3 \
    python3-pip \
    sudo \
    zsh \
    xrdp \
    kali-desktop-xfce \
    dbus-x11 \
    nano \
    vim \
    unzip \
    git \    
    && apt-get clean

COPY /scenario/Readme.txt /home/kaliuser/desktop/README.txt

# Création de l'utilisateur
RUN useradd -m -s /bin/bash kaliuser && echo "kaliuser:kali" | chpasswd && adduser kaliuser sudo

# Configurer XFCE comme environnement par défaut pour xrdp
RUN echo "startxfce4" > /home/kaliuser/.xsession && \
    chown kaliuser:kaliuser /home/kaliuser/.xsession

# Activer les services XRDP
RUN systemctl enable xrdp

# Exposer le port RDP
EXPOSE 3389

CMD ["/bin/bash", "-c", "dbus-daemon --system & /usr/sbin/xrdp-sesman & /usr/sbin/xrdp && tail -f /dev/null"]
