FROM docker.elastic.co/beats/filebeat:8.10.2

# Copier le fichier filebeat.yml dans l'image
COPY filebeat.yml /usr/share/filebeat/filebeat.yml

# Assurez-vous que le fichier appartient à root
USER root
RUN chmod go-w /usr/share/filebeat/filebeat.yml