FROM ubuntu:latest

# Mise à jour et installation de QEMU
RUN apt update && apt install -y qemu-system-x86 qemu-utils bridge-utils

# Créer le disque virtuel Windows de 50 Go
RUN qemu-img create -f qcow2 /opt/windows_disk.qcow2 50G

# Copier l'ISO de Windows, les pilotes Virtio et le fichier unattend.xml
COPY windows.iso /opt/windows.iso
COPY virtio.iso /opt/virtio-win.iso
COPY unattend.xml /opt/unattend.xml

# Lancer QEMU avec la configuration et ajouter l'ISO des pilotes Virtio
CMD qemu-system-x86_64 -enable-kvm -m 4G -smp 2 -boot d \
    -drive file=/opt/windows.iso,media=cdrom \
    -drive file=/opt/windows_disk.qcow2,if=ide,format=qcow2 \
    -netdev user,id=net0 -device e1000,netdev=net0 \
    -vnc :1

